name: common_business_rules_validators
description: Common business rules and algorithms for business in Brazil like CEP,CNPJ and CPF
version: 0.0.1
author: Sattva Company <daniel.vieira@sattva.company>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  
dev_dependencies:  
  test: 1.6.4
